### ISSUE TITLE
Unable to Run the Project

### ISSUE THREAD

**Issue by BurhanMughal** [markmansur/CoreML-Vision-demo#1]
Unable to read command while running the project.
<img width="854" alt="screen shot 2017-11-15 at 5 37 09 pm" src="https://user-images.githubusercontent.com/12183139/32836479-bbca9b2c-ca2b-11e7-84c2-0f2dae31306f.png">

**Comment by iambenmitchell** [comment]
Delete the mlmodel from xcode. Then find it in finder and drag and drop it in
